# Generated by Django 5.0 on 2023-12-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
