# Generated by Django 5.0 on 2023-12-22 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_payment_date_client_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='client',
            name='payment_day',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
    ]
